//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeniceNoel.Fusionner.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"NDA0MDJAMzEzNjJlMzMyZTMwQWgzcGVWSzIwVXlkL01sUUZDM2g2a0RJTXdzV0VWMEhmOCt1T2Qzb0kyUT0=;NDA0MDNAMzEzNjJlMzMyZTMwZnBoNlBtcDR2SkxMOVNCa2ZQeDk0RnphQmhxKy9tNlNhTndkK09VdG45MD0=;NDA0MDRAMzEzNjJlMzMyZTMwUCtONGN6V0E2UkFWS3EyU05iME5OTWpGMWFjd2kwY2tNWm9MYjRPNzVmdz0=;NDA0MDVAMzEzNjJlMzMyZTMwbjhNR3hmZFowNGVxYUJYcGIvZ2VXRG9seDNHOTRSZE1XSUtwWFNtQWw3Zz0=;NDA0MDZAMzEzNjJlMzMyZTMwVnQ4MVFHZ3hBSHVYRWJUNFNjdEI0UG4zbXBFNmJjNTNJSlhGaW56aFRIbz0=;NDA0MDdAMzEzNjJlMzMyZTMwZGd4T0QxT0FsUUVCR3ZNZSt3T0FmeFZNcmk5TlVCL1cxb3dxU3JzSWJNdz0=;NDA0MDhAMzEzNjJlMzMyZTMwS3J0MXdidnJoam11Q3QyYmtNUVRjYzlvUlFPcnJnckhHTDZKa3pQaGExMD0=;NDA0MDlAMzEzNjJlMzMyZTMwU0hKaVNtOW90SmFsWkM3R0NvMTljTnR0Y2pmaDEwaVJrZlNVS29Kdk5HRT0=;NDA0MTBAMzEzNjJlMzMyZTMwbW92ZEJNTmdvbmtRV24xd1NlL1MyaWJBeWJwd0FGcGxxWUY0dEJsU0hYOD0=")]
        public string SyncfusionLicense {
            get {
                return ((string)(this["SyncfusionLicense"]));
            }
        }
    }
}
